6/8/26. Trying to split the sample based on eye state AND self-report. Previous notebook only did eye state.

In [17]:
import pandas as pd

df = pd.read_csv("C:\\Users\\tempu\\Downloads\\research\\labs\\gratton\\Arousal-Project\\splitting_sample\\iNETs-sleep-data.csv")
df.head(5)

,file,subject,session,task,run,notes,sleep-score,FD-hold,category
0,sub-INET168_ses-4_task-rest_run-01_bold.nii.gz,INET168,4,rest,1,NaN,1,NaN,NaN
1,sub-INET168_ses-4_task-rest_run-02_bold.nii.gz,INET168,4,rest,2,NaN,1,NaN,NaN
2,sub-INET168_ses-4_task-rest_run-03_bold.nii.gz,INET168,4,rest,3,NaN,1,NaN,NaN
3,sub-INET168_ses-4_task-rest_run-04_bold.nii.gz,INET168,4,rest,4,NaN,2,NaN,NaN
4,sub-INET168_ses-4_task-rest_run-05_bold.nii.gz,INET168,4,rest,5,NaN,2,NaN,NaN

FD-hold is NaN because it's missing. Where do I get the FD info?  
Switching to MATLAB to make the df with time info.  
I don't think I can get the FD info. It's even missing in the QC sheets. I may have to trust this df is the best I can get.

In [20]:
df = df.drop("notes", axis=1)
df.head()

,file,subject,session,task,run,sleep-score,FD-hold,category
0,sub-INET168_ses-4_task-rest_run-01_bold.nii.gz,INET168,4,rest,1,1,NaN,NaN
1,sub-INET168_ses-4_task-rest_run-02_bold.nii.gz,INET168,4,rest,2,1,NaN,NaN
2,sub-INET168_ses-4_task-rest_run-03_bold.nii.gz,INET168,4,rest,3,1,NaN,NaN
3,sub-INET168_ses-4_task-rest_run-04_bold.nii.gz,INET168,4,rest,4,2,NaN,NaN
4,sub-INET168_ses-4_task-rest_run-05_bold.nii.gz,INET168,4,rest,5,2,NaN,NaN

In [30]:
cols = ['sleep-score', 'FD-hold', 'category']
len(df[df['sleep-score'].isna()]), len(df[df['FD-hold'].isna()]), len(df[df['category'].isna()])

(0, 589, 2449)

Most of category is NaN. Makes sense. I need to change the NaN to "eyes_opened" though.

In [31]:
df['category'] = df['category'].fillna('eyes_opened')

In [32]:
len(df[df['sleep-score'].isna()]), len(df[df['FD-hold'].isna()]), len(df[df['category'].isna()])

(0, 589, 0)

So FDs are the only issue. I don't think there's anything I can do about that though. But I can check. I'll make a list of the subjects I need to check for FD outputs.

In [40]:
df_fd = df[df['FD-hold'].isna()]
df_fd = df_fd.groupby('subject').agg('count').reset_index()
df_fd.subject

0     INET010
1     INET016
2     INET018
3     INET019
4     INET027
5     INET030
6     INET033
7     INET038
8     INET056
9     INET059
10    INET061
11    INET078
12    INET080
13    INET086
14    INET096
15    INET098
16    INET131
17    INET133
18    INET156
19    INET158
20    INET159
21    INET160
22    INET165
23    INET168
Name: subject, dtype: object

6/9. I'm checking the Sharepoint. Many of these FDs do exist. I can add them manually.  

6/10. I added them manually.

In [66]:
df = pd.read_csv("C:\\Users\\tempu\\Downloads\\research\\labs\\gratton\\Arousal-Project\\splitting_sample\\iNETs-sleep-data.csv")
df

,file,subject,session,task,run,notes,sleep-score,FD-hold,category
0,sub-INET168_ses-4_task-rest_run-01_bold.nii.gz,INET168,4,rest,1,NaN,1,0.959259259,NaN
1,sub-INET168_ses-4_task-rest_run-02_bold.nii.gz,INET168,4,rest,2,NaN,1,0.974074074,NaN
2,sub-INET168_ses-4_task-rest_run-03_bold.nii.gz,INET168,4,rest,3,NaN,1,0.974074074,NaN
3,sub-INET168_ses-4_task-rest_run-04_bold.nii.gz,INET168,4,rest,4,NaN,2,0.981481481,NaN
4,sub-INET168_ses-4_task-rest_run-05_bold.nii.gz,INET168,4,rest,5,NaN,2,0.977777778,NaN
...,...,...,...,...,...,...,...,...,...
2644,sub-INET001_ses-2_task-rest_run-07_bold.nii.gz,INET001,2,rest,7,NaN,1,0.95925925925925903,NaN
2645,sub-INET001_ses-2_task-rest_run-08_bold.nii.gz,INET001,2,rest,8,done after MRA/MRV,1,0.98148148148148195,movement
2646,sub-INET001_ses-1_task-rest_run-02_bold.nii.gz,INET001,1,rest,2,NaN,1,0.98148148148148195,NaN
2647,sub-INET001_ses-1_task-rest_run-03_bold.nii.gz,INET001,1,rest,3,NaN,1,0.98148148148148195,NaN
2648,sub-INET001_ses-1_task-rest_run-04_bold.nii.gz,INET001,1,rest,4,NaN,1,0.98148148148148195,NaN

In [67]:
## CLEANING

df = df.drop("notes", axis=1)
df['category'] = df['category'].fillna('eyes_opened')

# Drop the category == movement.
df = df[df['category'] != 'movement']

# Convert FD-hold to numeric.
df['FD-hold'] = df['FD-hold'].str.replace('\ufeff', '')
df["FD-hold"] = df["FD-hold"].astype(float)

len(df[df['sleep-score'].isna()]), len(df[df['FD-hold'].isna()]), len(df[df['category'].isna()])

(0, 6, 0)

In [68]:
df

,file,subject,session,task,run,sleep-score,FD-hold,category
0,sub-INET168_ses-4_task-rest_run-01_bold.nii.gz,INET168,4,rest,1,1,0.959259,eyes_opened
1,sub-INET168_ses-4_task-rest_run-02_bold.nii.gz,INET168,4,rest,2,1,0.974074,eyes_opened
2,sub-INET168_ses-4_task-rest_run-03_bold.nii.gz,INET168,4,rest,3,1,0.974074,eyes_opened
3,sub-INET168_ses-4_task-rest_run-04_bold.nii.gz,INET168,4,rest,4,2,0.981481,eyes_opened
4,sub-INET168_ses-4_task-rest_run-05_bold.nii.gz,INET168,4,rest,5,2,0.977778,eyes_opened
...,...,...,...,...,...,...,...,...
2643,sub-INET001_ses-2_task-rest_run-06_bold.nii.gz,INET001,2,rest,6,1,0.970370,eyes_opened
2644,sub-INET001_ses-2_task-rest_run-07_bold.nii.gz,INET001,2,rest,7,1,0.959259,eyes_opened
2646,sub-INET001_ses-1_task-rest_run-02_bold.nii.gz,INET001,1,rest,2,1,0.981481,eyes_opened
2647,sub-INET001_ses-1_task-rest_run-03_bold.nii.gz,INET001,1,rest,3,1,0.981481,eyes_opened
2648,sub-INET001_ses-1_task-rest_run-04_bold.nii.gz,INET001,1,rest,4,1,0.981481,eyes_opened

In [70]:
INET_TR = 1.1
INET_FRAMES = 450

df["time"] = ((INET_FRAMES * df["FD-hold"]) * INET_TR) / 60
df

,file,subject,session,task,run,sleep-score,FD-hold,category,time
0,sub-INET168_ses-4_task-rest_run-01_bold.nii.gz,INET168,4,rest,1,1,0.959259,eyes_opened,7.913889
1,sub-INET168_ses-4_task-rest_run-02_bold.nii.gz,INET168,4,rest,2,1,0.974074,eyes_opened,8.036111
2,sub-INET168_ses-4_task-rest_run-03_bold.nii.gz,INET168,4,rest,3,1,0.974074,eyes_opened,8.036111
3,sub-INET168_ses-4_task-rest_run-04_bold.nii.gz,INET168,4,rest,4,2,0.981481,eyes_opened,8.097222
4,sub-INET168_ses-4_task-rest_run-05_bold.nii.gz,INET168,4,rest,5,2,0.977778,eyes_opened,8.066667
...,...,...,...,...,...,...,...,...,...
2643,sub-INET001_ses-2_task-rest_run-06_bold.nii.gz,INET001,2,rest,6,1,0.970370,eyes_opened,8.005556
2644,sub-INET001_ses-2_task-rest_run-07_bold.nii.gz,INET001,2,rest,7,1,0.959259,eyes_opened,7.913889
2646,sub-INET001_ses-1_task-rest_run-02_bold.nii.gz,INET001,1,rest,2,1,0.981481,eyes_opened,8.097222
2647,sub-INET001_ses-1_task-rest_run-03_bold.nii.gz,INET001,1,rest,3,1,0.981481,eyes_opened,8.097222
2648,sub-INET001_ses-1_task-rest_run-04_bold.nii.gz,INET001,1,rest,4,1,0.981481,eyes_opened,8.097222

### Low Arousal Group

In [86]:
# Split the data into high and low arousal based on sleep-score and category.

df_low = df[((df["sleep-score"] > 5) | (df["category"] == "eyes_closed"))]

# Group by subject and aggregate by sum for time.
cols = ['file', 'session', 'task', 'run', 'sleep-score', 'FD-hold', 'category']
df_low_time = df_low.drop(cols, axis=1)
df_low_time = df_low_time.groupby("subject").agg({"time": "sum"})

# Fill in the subject's time for all runs.
df_low["total_time"] = df_low["subject"].map(df_low_time["time"])

# For merging
df_low["arousal_group"] = "low"

df_low.describe()

C:\Users\tempu\AppData\Local\Temp\ipykernel_21472\1032841309.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_low["total_time"] = df_low["subject"].map(df_low_time["time"])
C:\Users\tempu\AppData\Local\Temp\ipykernel_21472\1032841309.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_low["arousal_group"] = "low"

          session         run  sleep-score     FD-hold        time  total_time
count  305.000000  305.000000   305.000000  305.000000  305.000000  305.000000
mean     2.465574    4.157377     4.940984    0.896120    7.392987   55.807969
std      1.146919    1.779309     1.759315    0.126501    1.043631   32.960280
min      1.000000    1.000000     1.000000    0.296296    2.444444    2.536111
25%      1.000000    3.000000     4.000000    0.877778    7.241667   30.769444
50%      2.000000    4.000000     6.000000    0.948148    7.822222   48.247222
75%      4.000000    6.000000     6.000000    0.974074    8.036111   69.772222
max      4.000000    8.000000     7.000000    0.981481    8.097222  134.597222

In [87]:
df_low_group = df_low[df_low["total_time"] >= 5]
df_low_prec = df_low[df_low["total_time"] >= 20]

df_low_group.shape, df_low_prec.shape

((303, 11), (266, 11))

In [93]:
len(df_low_prec.subject.unique())

39

### High Arousal Group

In [89]:
df_high = df[((df["sleep-score"] < 3) | (df["category"] == "eyes_opened"))]

# Group by subject and aggregate by sum for time.
cols = ['file', 'session', 'task', 'run', 'sleep-score', 'FD-hold', 'category']
df_high_time = df_high.drop(cols, axis=1)
df_high_time = df_high_time.groupby("subject").agg({"time": "sum"})

# Fill in the subject's time for all runs.
df_high["total_time"] = df_high["subject"].map(df_high_time["time"])

# For merging
df_high["arousal_group"] = "high"

df_high.describe()

C:\Users\tempu\AppData\Local\Temp\ipykernel_21472\4096090146.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_high["total_time"] = df_high["subject"].map(df_high_time["time"])
C:\Users\tempu\AppData\Local\Temp\ipykernel_21472\4096090146.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_high["arousal_group"] = "high"

,session,run,sleep-score,FD-hold,time,total_time
count,2465.000000,2465.000000,2465.000000,2459.000000,2459.000000,2465.000000
mean,2.569980,4.167546,2.909939,0.920823,7.596787,206.323323
std,1.128903,2.147352,1.514005,0.105839,0.873171,33.691207
min,1.000000,1.000000,1.000000,0.051852,0.427778,56.191667
25%,2.000000,2.000000,2.000000,0.911111,7.516667,187.030556
50%,3.000000,4.000000,3.000000,0.966667,7.975000,211.475000
75%,4.000000,6.000000,4.000000,0.977778,8.066667,233.475000
max,5.000000,9.000000,7.000000,0.984091,8.118750,256.452778

In [90]:
df_high_group = df_high[df_high["total_time"] >= 5]
df_high_prec = df_high[df_high["total_time"] >= 20]

df_high_group.shape, df_high_prec.shape

((2465, 11), (2465, 11))

### Finalizing Samples   

## GROUP

In [ ]:
# Create a set of (subject, session, run) tuples from df_low
low_keys = set(zip(df_low['subject'], df_low['session'], df_low['run']))

# Assign "low" or "high" based on membership
df['arousal_group'] = df.apply(lambda row: 'low' if (row['subject'], row['session'], row['run']) in low_keys else 'high', axis=1)

,file,subject,session,task,run,sleep-score,FD-hold,category,time,arousal_group
0,sub-INET168_ses-4_task-rest_run-01_bold.nii.gz,INET168,4,rest,1,1,0.959259,eyes_opened,7.913889,high
1,sub-INET168_ses-4_task-rest_run-02_bold.nii.gz,INET168,4,rest,2,1,0.974074,eyes_opened,8.036111,high
2,sub-INET168_ses-4_task-rest_run-03_bold.nii.gz,INET168,4,rest,3,1,0.974074,eyes_opened,8.036111,high
3,sub-INET168_ses-4_task-rest_run-04_bold.nii.gz,INET168,4,rest,4,2,0.981481,eyes_opened,8.097222,high
4,sub-INET168_ses-4_task-rest_run-05_bold.nii.gz,INET168,4,rest,5,2,0.977778,eyes_opened,8.066667,high
...,...,...,...,...,...,...,...,...,...,...
2643,sub-INET001_ses-2_task-rest_run-06_bold.nii.gz,INET001,2,rest,6,1,0.970370,eyes_opened,8.005556,high
2644,sub-INET001_ses-2_task-rest_run-07_bold.nii.gz,INET001,2,rest,7,1,0.959259,eyes_opened,7.913889,high
2646,sub-INET001_ses-1_task-rest_run-02_bold.nii.gz,INET001,1,rest,2,1,0.981481,eyes_opened,8.097222,high
2647,sub-INET001_ses-1_task-rest_run-03_bold.nii.gz,INET001,1,rest,3,1,0.981481,eyes_opened,8.097222,high
2648,sub-INET001_ses-1_task-rest_run-04_bold.nii.gz,INET001,1,rest,4,1,0.981481,eyes_opened,8.097222,high

In [97]:
df.to_csv("C:\\Users\\tempu\\Downloads\\research\\labs\\gratton\\Arousal-Project\\splitting_sample\\larger_sample\\larger_sample.csv", index=False)